### ISSUE TITLE
Missing value for TIFF images

### ISSUE THREAD

**Issue by peterbandi** [computationalpathologygroup/ASAP#102]
It would be very useful if the value of the missing parts could be set in the multiresolutionimageinterface of ASAP. For example when loading image patches from RGB TIFF images, I would like to configure it to return white color where the TIFF does not contain information. While for mask (gray-scale) images I would like to configure the value to back. It is only necessary for TIFF images.

**Comment by GeertLitjens** [comment]
This is now implemented
