### ISSUE TITLE
MultiResolutionImageReader.open(file_name) will return None with latest open-slide 

### ISSUE THREAD

**Issue by nchos88** [computationalpathologygroup/ASAP#104]
OS : Windows 10 64bits 
Open-slide version : 2017-11-22 Windows Binaries
Python version ; 3.6
Data : camelyon16

```
import multiresolutionimageinterface as mir
import os.path as osp
import openslide
import matplotlib.pyplot as plt
from pathlib import Path
import glob

slide_path = r'D:\0_jobProgram\data\Camelyon16\tumor'

tumor_paths = glob.glob(osp.join(slide_path, '*.tif'))
tumor_paths.sort()

reader = mir.MultiResolutionImageReader()

#read img
testpath = tumor_paths[0]
mr_image = reader.open(slide_path) # return none

```

**Comment by lvguofeng1303** [comment]
I also met same problem, Can you solve it and How? 
thank！

**Comment by GeertLitjens** [comment]
I'm sorry, I can't seem to reproduce this. Which version of ASAP are you using? Could you try redownloading a file from the CAMELYON16 Google Drive and using that?

**Comment by lvguofeng1303** [comment]
> I'm sorry, I can't seem to reproduce this. Which version of ASAP are you using? Could you try redownloading a file from the CAMELYON16 Google Drive and using that?

I think I have successfully installed ASAP， cause i can successfully import multiresolutionimageinterface， but i dont know what return None. What should i do？

**Comment by hmkim** [comment]
With version 1.9 of ASAP, it works well.

And I think ASAP must have the check routine for open-slide installing.

In my case, after install the open-slide, None issue is solved.

**Comment by nchos88** [comment]
> I'm sorry, I can't seem to reproduce this. Which version of ASAP are you using? Could you try redownloading a file from the CAMELYON16 Google Drive and using that?

File is ok. ASAP viewer work well. 

Additionally i found other problem.

**If i import openslide , asap can't read image, but without import openslide, asap work well** 

I tried with asap 1,7.0 ~ 1.9.0 and get same result.

**Comment by GeertLitjens** [comment]
Quite sure this is caused by mixing different version of the libopenslide.dll. One is provided with ASAP. If you have another installed on your system which is picked up by openslide-python you will get conflicts. So make sure you only have one version
