### ISSUE TITLE
when it can support KFB Format

### ISSUE THREAD

**Issue by WyHy** [computationalpathologygroup/ASAP#105]
Hi, thanks for your work. It helps me a lot.
I am very grateful that you can support the kfb format pathology image. Do you have such a plan now?
here is a sample download url: 
https://pan.baidu.com/s/1vDRF9YENOXmti9Em6QNaRw 
extract code：71kg 

thanks again!

**Comment by GeertLitjens** [comment]
Hi, to be able to support this we would need a description of the file format or some open-source code with an appropriate license. We don't have the expertise to reverse engineer a file format ourselves.
