### ISSUE TITLE
libpugixml.so not linked

### ISSUE THREAD

**Issue by fkluknav** [computationalpathologygroup/ASAP#106]
Hi,
when building ASAP, it insists that pugixml.cpp must be available. Even if PUGIXML_HEADER_ONLY is not defined in pugiconfig.hpp.
When I edit pugixml.hpp to really not include the whole source file, compilation works but linking fails because of missing symbols - libpugixml.so is never linked.
Is this by design? Am I doing something wrong?
My goal is to package ASAP for Fedora and CentOS, build a flatpak etc. to, well, be able to conveniently use ASAP. All needed libraries are nicely available in the distro but not really working.

**Comment by GeertLitjens** [comment]
This is on purpose to prevent the user needing to install a PugiXML package on their system, which we had some issues with in the past (e.g. package not getting updated). We enforce this way of building by giving a compiler definition. The easiest way to compile yourself is to compile pugixml from source and then copying the CPP to the include dir after make install. That should fix the issue.

**Comment by fkluknav** [comment]
Of course I can include the cpp by hand on my machine and compile asap on my machine. My point is, to officially package ASAP for a few linux distributions, it must build using packages already available in those distributions. Randomly messing with them is not an option. Including a second copy of pungixml with ASAP is, again, forbidden as a principle.
It is definitely your right to decide you do not want to support it. I can only suggest that, maybe, it is in your best interest as well - having users install ASAP by clicking on an icon instead of compiling (and learning what compilation is and what cmake is and what libraries are).
About pugixml not updated, I do not understand the problem. I would guess that including the whole source is exactly what causes pugixml to never being updated, because it is statically compiled in, instead of being a dynamic library that can be updated automatically anytime. But I must believe you.

**Comment by GeertLitjens** [comment]
The point is that because we use the header only feature (which was implemented by the PugiXML developers, see here: https://pugixml.org/docs/manual.html) we do not need the PugiXML package at all at install time. I just checked for our latest release (1.9) on Ubuntu 16.04 and 18.04 and it is as simple as clicking the .deb file and pressing install.

**Comment by fkluknav** [comment]
Ubuntu may not be the only relevant distro in the world. People forced to use machines managed by their IT department at work and not allowed to install random software must resort to awkwardness like in-browser cytomine. Or people who also want to use a different tool for, unfortunately, a different operating system. But of course this is only my personal opinion.  I respect your decision. I am sorry to have wasted your time. Thank you for the explanation.
