### ISSUE TITLE
modify TIFF mask

### ISSUE THREAD

**Issue by manutdzou** [computationalpathologygroup/ASAP#110]
Thanks for your great work! In this work it supports annotation in "xml" and save as xml or tiff format for lable. However after annotation, I save the annotation label as tiff format for overlay, is there any possible to modify the tiff format label in the ASAP?  I think this is very helpful for semi-automatic labeling!

**Comment by GeertLitjens** [comment]
This is something on our wish list, but we have really looked at how  to implement this
