### ISSUE TITLE
TIFF mask label to xml

### ISSUE THREAD

**Issue by manutdzou** [computationalpathologygroup/ASAP#111]
Thanks for your great project. In this project it can cover annotation from xml format to tiff format. However is there any possible to cover annotation from tiff format to xml format.

**Comment by GeertLitjens** [comment]
I've used this example in the past to generate polygons from mask images: http://scikit-image.org/docs/dev/auto_examples/edges/plot_contours.html. Then you can write out an XML file from the polygon coordinates:

**Comment by hutaohutc** [comment]
Could you please show me an example how to write out an XML file from the polygon coordinates? Thanks @GeertLitjens
