### ISSUE TITLE
how to install the ASAP on CentOS7？

### ISSUE THREAD

**Issue by Merryang** [computationalpathologygroup/ASAP#113]
How to install ASAP on CentOS7？
I haven't found the guide on installing ASAP on CentOS, and errors occurred when I installed OpenCV,
have anyone successfully installed ASAP on CentOS? What's the steps? Thanks a lot.

**Comment by GeertLitjens** [comment]
Hi, we do not officially support distributions outside of the Ubuntu-family. You can probably get it to work, but we have no resources to support you in this endeavor
