### ISSUE TITLE
Request: Keyboard shortcut to toggle on/off overlay image

### ISSUE THREAD

**Issue by oscargeessink** [computationalpathologygroup/ASAP#120]
It would be really useful if the visualization of overlay images could be toggled on/off via a hotkey or keyboard shortcut in addition to the current option of using the _"Enable visualization"_ tick box on the _Overlays_ tab. 
Motivation: Since I often have to check large amounts of manual annotations in relation to classification maps / heatmaps, it would be much better if I didn't have to repeatedly move between the _Annotations_ tab and _Overlays_ tab. Of course, I often try different _Opacity_ values, but most of the times, just toggling the overlay images on/off works best for me.

**Comment by GeertLitjens** [comment]
Done in the new version
