### ISSUE TITLE
MultiResolutionImageReader.open(file_name) will return None with ASAP 1.9 in ubuntu

### ISSUE THREAD

**Issue by euwern** [computationalpathologygroup/ASAP#123]
OS: ubuntu 16.04.4 LTS
ASAP version: 1.9
```
import multiresolutionimageinterface as mir
reader = mir.MultiResolutionImageReader()
mr_image = reader.open('../CAMELYON16/training/tumor/tumor_036.tif')
print(type(mr_image))
mr_image.getDimensions() #error
```
I have tried entering the full path and renaming the file to '.tiff' but it didn't work too.
May I know how to resolve this?

**Comment by GeertLitjens** [comment]
Hi, please try installing the libopenslide-dev package, probably that is missing

**Comment by euwern** [comment]
Thank you. It works after installing the recommended package.
