### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by wanghan0501** [computationalpathologygroup/ASAP#125]
You said:
```
To help developers compile this software themselves we provide the necesarry binaries (Visual Studio 2013, 64-bit) for all third party libraries on Windows except Boost, OpenCV and Qt (due to size constraints).

...

To compile the source code yourself, first make sure all third-party libraries are installed.
```
I am fresh person in developing ASAP. I have a question that is  how can I install third-party in my Windows-PC while using VS Studio 2013. I mean such as `libtiff `,`libjpeg `.

**Comment by GeertLitjens** [comment]
We don't provide precompiled third pary libraries for VS 2013, so either you have to download those dependencies from the developers or compile them yourself.
