### ISSUE TITLE
Error: PulgiXML 

### ISSUE THREAD

**Issue by wanghan0501** [computationalpathologygroup/ASAP#126]
```
CMake Error at CMakeLists.txt:59 (find_package):
  By not providing "FindPugiXML.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PugiXML", but
  CMake did not find one.

  Could not find a package configuration file provided by "PugiXML" with any
  of the following names:

    PugiXMLConfig.cmake
    pugixml-config.cmake

  Add the installation prefix of "PugiXML" to CMAKE_PREFIX_PATH or set
  "PugiXML_DIR" to a directory containing one of the above files.  If
  "PugiXML" provides a separate development package or SDK, be sure it has
  been installed.

```

What should I do?

**Comment by GeertLitjens** [comment]
If you compile PugiXML yourself and then build the install target you should get a folder which contains PugiXMLConfig.cmake, you should point CMake to that folder. I'm guessing when you install a developer provided binary these files are also included, so point CMake there.

**Comment by BelalC** [comment]
I'm getting the same error after running 'cmake' for ASAP-1.9. I have already installed pugixml via `apt install libpugixml-dev libpugixml1v5`.

I also successfully compiled PugiXML; but I can't see any files with the name "PugiXMLConfig.cmake" or "pugixml-config.cmake"

I'm running on Ubuntu 18.04. This is the error I get trying to cmake ASAP-1.9:

`CMake Error at CMakeLists.txt:56 (find_package):
  By not providing "FindPugiXML.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PugiXML", but
  CMake did not find one.

  Could not find a package configuration file provided by "PugiXML" with any
  of the following names:

    PugiXMLConfig.cmake
    pugixml-config.cmake

  Add the installation prefix of "PugiXML" to CMAKE_PREFIX_PATH or set
  "PugiXML_DIR" to a directory containing one of the above files.  If
  "PugiXML" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/paperspace/ASAP-1.9/build/CMakeFiles/CMakeOutput.log".
See also "/home/paperspace/ASAP-1.9/build/CMakeFiles/CMakeError.log".`


I'd really appreciate any clarification or advice on how to proceed! Please let me know if I've missed out any information required!
