### ISSUE TITLE
Question: How does ASAP save annotations on Multilevel? 

### ISSUE THREAD

**Issue by euwern** [computationalpathologygroup/ASAP#127]
In the CAMELYON17 dataset page, there are some code to save xml annotations as tif file. But when I looked at the evaluation script, the evaluation mask is created based on level=5, which means there are some resizing done on the annotations (since the annotation is based on level=0). 

Does ASAP applied a bilinear interpolation when resizing annotation at a lower zoom level? If not what operation does it do to get evaluation mask at level=5 from level=0?

**Comment by GeertLitjens** [comment]
ASAP generates the mask at level 0, but stores a multi-resolution pyramid. For creation of the evaluation mask the fifth resolution level is used. ASAP can do both bilinear interpolation and nearest neigbor to create these resolution levels, in the case of binary mask images nearest neigbor should be used (and is in this case).
