### ISSUE TITLE
Annotation mask generated is incorrect when compared to xml annotation. 

### ISSUE THREAD

**Issue by euwern** [computationalpathologygroup/ASAP#128]
I am facing some problem with the annotation of CAMELYON16 test data. I use the code provided to generate annotation mask but when I try to count the number of tumors inside the mask, it returns only 1 or 0. which is wrong as the xml file has more than 1 tumor. For example: test_030.xml has 76 tumors annotation but the generated mask tif file returns 1 tumor. I provided a sample of my code to recreate the problem. 

Can someone help me to identify the problem? 

## convert xml to tif 
```
import multiresolutionimageinterface as mir
reader = mir.MultiResolutionImageReader()
mr_image = reader.open('/mnt/datasets/camelyon16/testing/images/test_030.tif')
annotation_list = mir.AnnotationList()
xml_repository = mir.XmlRepository(annotation_list)
xml_repository.setSource('/mnt/datasets/camelyon16/testing/anno/test_030.xml')
xml_repository.load()
annotation_mask = mir.AnnotationToMask()
camelyon17_type_mask = False
label_map = {'metastases': 1, 'normal': 2} if camelyon17_type_mask else {'_0': 1, '_1': 1, '_2': 0}
conversion_order = ['metastases', 'normal'] if camelyon17_type_mask else  ['_0', '_1', '_2']
output_path = '/mnt/datasets/camelyon16/testing/masks/test_030_mask.tif'
annotation_mask.convert(annotation_list, output_path, mr_image.getDimensions(), mr_image.getSpacing(), label_map, conversion_order)
```

## evaluation mask
```
#note: code obtained from evaluation script
def computeEvaluationMask(maskDIR, resolution, level):
    """Computes the evaluation mask.
    
    Args:
        maskDIR:    the directory of the ground truth mask
        resolution: Pixel resolution of the image at level 0
        level:      The level at which the evaluation mask is made
        
    Returns:
        evaluation_mask
    """
    slide = openslide.open_slide(maskDIR)
    dims = slide.level_dimensions[level]
    pixelarray = np.zeros(dims[0]*dims[1], dtype='uint')
    pixelarray = np.array(slide.read_region((0,0), level, dims))
    distance = nd.distance_transform_edt(255 - pixelarray[:,:,0])
    Threshold = 75/(resolution * pow(2, level) * 2) # 75µm is the equivalent size of 5 tumor cells
    binary = distance < Threshold
    filled_image = nd.morphology.binary_fill_holes(binary)
    evaluation_mask = measure.label(filled_image, connectivity = 2) 
    return evaluation_mask

mask_path = '/mnt/datasets/camelyon16/testing/masks/test_030_mask.tif'
EVALUATION_MASK_LEVEL = 5 # Image level at which the evaluation is done
L0_RESOLUTION = 0.243 # pixel resolution at level 0
eval_mask = computeEvaluationMask(mask_path, L0_RESOLUTION, EVALUATION_MASK_LEVEL)
print(np.amax(eval_mask))
```

**Comment by GeertLitjens** [comment]
Hi, it is better to ask these CAMELYON specific questions in the CAMELYON forum. Could you post an image of the tif you obtain via the conversion of the XML? You can either open the mask image in ASAP or  use matplotlib and imshow to show a low-resolution version. Note that the TIFF file will be binary (e.g. the max value will be 1, not every tumor annotation will get a separate label).

**Comment by euwern** [comment]
Hi @GeertLitjens  I apologize for posting CAMELYON specific question in ASAP github. Thanks for mentioning. I think there is something wrong with the function provided by the evaluation script (I.e. the threshold and binary hole filling are messing with the tiff masks).

As suggested, I generated a preview of the tiff mask and it looks correct. This shows that there is nothing wrong with ASAP. (attached image).

Thanks for your debugging tips. 

![tumor masks for test_030](https://lh3.googleusercontent.com/Po88pDi6L3Vm-9fcqkKz8TA-LAc8Brm8PTbmY51_p4LXfg2KdskcFfsGJ9u8S33vLuU3fzRN_cI-IFxKhDyslH5J3od6IY_4CY-X2Gjtyx3BfhDdP7jaJP1kLA1UmcK9woA9n2Ir9mq01PwF_HqI7IJc2WH4R25sjrtkceJDYKpkC6gu7CDdQ2DR9pJphmX7UxifmkY8WPZMkafjKjzONBqFud8rD3fXP4xDWxEbtJ6xrb5OCMpVI7RAH9BBEMhI0keWYVlN4I27c3L5YKeyTWatohicgqBHUmcW6MxLbRFcW1TXmdZA-TY3ukh3zkvb8cG2zv8_ULm3Kr9gSx_CI8iBnT2aUzZbEqKZ_jpdntjaqQF4JWsJAuluBFDX45CNfN4wic5C7LF0ftijXcq8vbxcBkzfkY5sQTrajsLzioj2gHbjXUPRX7G6LA2YQKx6lah4DYKNhMVvB7oYw4ptrDREZCPoT5d0dLq-EIwLogZa7AehXUbQ4OE84ASEV7bde1XQXhR74PgngfnDoClhtRBijmfX-45D35Q_LOb7UY4fejGnXzeIbsKyk7HhGnmp3HrTYUmIPjWGFEdEvY6WXMaMX-4w-0g-wOMjbrN1_20LDwbqX4VmaLgRixD-ujQr2lG55FzZuyWLrvPeJMs1ZJPQbDfEmgjD=w373-h842-no)

**Comment by christinesu12** [comment]
> 嗨@GeertLitjens 我很抱歉在ASAP github中發布有關CAMELYON的特定問題。感謝您的提及。我認為評估腳本提供的功能有問題（即閾值和二進制填充孔使tiff蒙版混亂了）。
> 
> 如建議的那樣，我生成了tiff遮罩的預覽，看起來很正確。這表明ASAP沒有錯。（附圖）。
> 
> 感謝您的調試提示。
> 
> ![test_030的腫瘤口罩](https://camo.githubusercontent.com/9f494365d834e2010053f511eb2a0e78ea73d801/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f506f3838704469364c33566d2d396663716b4b7a3854412d4c41633842726d385054626d5935315f70344c586667324b64736b63466673474a397538533333764c755533667a524e5f63492d4946784b684479736c48354a336f643649595f3443592d5832476a74797833426668446450376a614a50316b4c4131556d634b39776f41396e324972396d7130315077465f48714937494a6332574834523235736a72746b63654a44594b706b43366775374344645132445239704a70686d5837557869666d6b593857505a4d6b61666a4b6a7a4f4e42714675643872443366585034784457784562744a36787262354f434d70564937524148394242454d6849306b655759566c4e3449323763334c35594b6579545761746f68696367714248556d6357364d784c62524663573154586d645a412d545933756b68337a6b7662386347327a76385f554c6d334b72396753785f43493869426e543261557a5a6245714b5a5f6a70646e746a61715146344a57734a41756c75424644583435434e664e347769633543374c46306674696a5863713876627863426b7a666b593573515472616a734c7a696f6a326748626a58555052583747364c413259514b78366c61683444594b4e684d567642376f5977347074724452455a43506f54356430644c712d4549774c6f675a613741656858556251344f4538344153455637626465315851586852373450676e67666e446f436c68745242696a6d66582d3435443335515f4c4f623755593466656a476e587a654962734b796b374868476e6d703348725459556d49506a57474645644576593657584d614d582d34772d30672d774f4d6a62724e315f32304c447762715834566d614c67526978442d756a5172326c473535467a5a7579574c727650654a4d73315a4a5051624466456d676a443d773337332d683834322d6e6f)

i have the same question with you,do you have the solution to this problem?

**Comment by Reasat** [comment]
Where is the Camelyon forum?
