### ISSUE TITLE
precompiled third pary libraries for VS 2017

### ISSUE THREAD

**Issue by wanghan0501** [computationalpathologygroup/ASAP#129]
could you provide precompiled third pary libraries for VS 2017?

**Comment by wanghan0501** [comment]
Can you provide them for developers?

**Comment by GeertLitjens** [comment]
Hi, you can find those on the releases page for most dependencies (no OpenCV, boost) here: https://github.com/computationalpathologygroup/ASAP/releases/download/1.6/ThirdParty.7z

**Comment by wanghan0501** [comment]
![error](https://user-images.githubusercontent.com/13730405/54084137-e984d580-4367-11e9-82b0-1c0b0131f7dd.png)
However, when I compile ASAP-1.9, I meet the error shown in figure.  I think may be I should use latest `libtiff.lib` . Could you release them for us?
