### ISSUE TITLE
CMake error（on win10）: PYTHON_DEBUG_LIBRARY

### ISSUE THREAD

**Issue by ypsprimer** [computationalpathologygroup/ASAP#132]
When I use CMake to configure WRAP_MULTIRESOLUTIONIMAGEINTERFACE_PYTHON and WRAP_WHOLESLIDEFILTERS_PYTHON, errors occur:

**CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_DEBUG_LIBRARY (ADVANCED)
    linked by target "_multiresolutionimageinterface" in directory D:/ASAP-develop/ASAP-develop/multiresolutionimageinterface
    linked by target "_wholeslidefilters" in directory D:/ASAP-develop/ASAP-develop/imgproc/wholeslide**

However, I have installed python before from Anaconda and I could not find the path containing lib files of python. Should I need to re-download python from another source?
Also, what are the functions of WRAP_MULTIRESOLUTIONIMAGEINTERFACE_PYTHON and WRAP_WHOLESLIDEFILTERS_PYTHON, could ASAP start up without them?

**Comment by GeertLitjens** [comment]
Anaconda does have the required python libraries. You can check which one it has selected by toggling the advanced parameters in CMake and then searching for Python. If you don't have the Python debug library (most likely) you can simply point it to the Release python.lib.
