### ISSUE TITLE
Incomplete UI when ASAP start up

### ISSUE THREAD

**Issue by ypsprimer** [computationalpathologygroup/ASAP#133]
I have successfully used CMake to configure the folder named ASAP-develop and VS2017 to compile it. No errors occurred during the process of configuring and compiling, and when the program starts up, the UI shows. 

However, this UI is incomplete, it is lack of several buttons for annotation,  pan, zoom, measure and so on. Also it does not have the function of image preprocessing. This UI could only be used to open a .tiff file and display it.

Is there something I ignore to do or need to set up? ( I did not choose to configure WRAP_MULTIRESOLUTIONIMAGEINTERFACE_PYTHON and WRAP_WHOLESLIDEFILTERS_PYTHON, does it has something to do with my problem? )

**Comment by x7qiu** [comment]
Same problem here, compiled with the provided 3rd party libs on VS2013. No errors, but the APP has no annotation bar and cannot read as many file formats as the released version. 

I noticed that compared to the released version my ASAP folder is missing a lot of DLLs (they are all successfully compiled, just not in the ASAP folder) so maybe that has something to do with it. Trying to move them  manually and see if it makes a difference.

This is my first time using Cmake and Visual studio tho so I'm probably missing something simple. Appreciate any help & tips.

**Comment by GeertLitjens** [comment]
You need to build the INSTALL target, which automatically copies all the required files to the correct folders. You can specify the install location in CMake via the CMAKE_INSTALL_PREFIX variable

**Comment by HenryNebula** [comment]
I am confused about the meaning of "build the INSTALL target". Does it mean "make install"? I tried that after "make" and it does appear in CMAKE_INSTALL_PREFIX directory, but some .so files are missing and the UI is not complete. Am I doing something wrong here?

**Comment by WxpHB** [comment]
Same problem, does someone solve it? help me out......
