### ISSUE TITLE
Provided 3rd party library compatible with vs2013 or vs2017?

### ISSUE THREAD

**Issue by x7qiu** [computationalpathologygroup/ASAP#135]
Hi. I noticed on Readme it says 

> To help developers compile this software themselves we provide the necesarry binaries (Visual Studio 2013, 64-bit) for all third party libraries on Windows except Boost, OpenCV and Qt

But in #129 it seems these 3rd party libraries are compatible with VS 2017. As I understand, binaries compiled with different versions of Visual Studio are not guranteed to be compatible. So can you clearify  which VS should we use? Thanks.

(I tried compile the code myself but am encoutering other problems unrelated to the compilatin process so I can't tell if it's a compatibility issue.)

**Comment by GeertLitjens** [comment]
Hi, we provided both in the past, you can find them on the Releases page (just search for third party). However, we are no longer actively supporting VS2013, so I highly recommend upgrading to VS2017
