### ISSUE TITLE
multiresolutionimageinterface only build

### ISSUE THREAD

**Issue by peterbandi** [computationalpathologygroup/ASAP#137]
It would be very useful to have a multiresolutionimageinterface only build with python bindings. Installing the current ASAP deb on our cluster triggers the installation of a lot of packages that are never used because of the GUI components.

**Comment by AlistairSymonds** [comment]
Going to give this a plus one of support as well, also on the topic of python APIs would it be possible for a conda/pip distribution?

**Comment by GeertLitjens** [comment]
This is possible, you can have a look at the .appveyor and the docker file in the buildtools directory to see how to do this. Pip and conda support are on the list, but I have to figure out how to handle the complications with the dependencies
