### ISSUE TITLE
Annotation done in other zoom level is not correct

### ISSUE THREAD

**Issue by euwern** [computationalpathologygroup/ASAP#142]
I notice that the polygon annotation done in other zoom level (say: 9000 pixel) is not correct when viewed in (3000 pixel). See attached images. 

Annotation done in (9000pixel)
https://bit.ly/2UgkpVO

Annotation viewed in (3000 pixel)
https://bit.ly/2Uq2VWU

**Comment by GeertLitjens** [comment]
Annotations are always stored with pixel coordinates at the highest resolution. You can convert resolutions by getting the requested level downsample and dividing the coordinates (getLevelDownsample member function on an image)

**Comment by euwern** [comment]
> Annotations are always stored with pixel coordinates at the highest resolution. You can convert resolutions by getting the requested level downsample and dividing the coordinates (getLevelDownsample member function on an image)

But there is a bug in the ASAP program.  Since Annotation viewed in ASAP (at 3000 pixel) is different from Annotation done (in 9000 pixel). Is this going to be fixed?

**Comment by GeertLitjens** [comment]
I'm sorry, I don't know what you mean exactly and the links to the images you posted don't work.

**Comment by euwern** [comment]
Annotation done in (9000pixel)
![zz](https://user-images.githubusercontent.com/588479/60270778-17fad200-98bf-11e9-888f-4c4ed4c2251f.png)

Annotation viewed in (3000 pixel)
![zz1](https://user-images.githubusercontent.com/588479/60270769-15987800-98bf-11e9-8505-b24e8560a024.png)

**Comment by GeertLitjens** [comment]
Hmm, I have not seen this before. What filetype are you using with which version of ASAP (+ operating system)

**Comment by euwern** [comment]
- Ubuntu 16.04.4 LTS
- ASAP 1.9.0
filetype = .tif 
dataset source = camelyon16

**Comment by GeertLitjens** [comment]
Ok, so I'm guessing this is related to an outdated version of OpenSlide. You need version 3.4.1 which is not in the standard repositories of Ubuntu 16.04, only from 17 on. So you need to install that manually, or upgrade Ubuntu. If you install it manually do not forget to remove the old 3.4.0 package

**Comment by euwern** [comment]
ok, the suggested solution works. Thanks. 

I have another question, when I am annotating with polygon, how can I navigate my viewpoint? By switching from PolyAnnotation to Span mode I lose the annotation.

**Comment by GeertLitjens** [comment]
You can press the mouse wheel to pan and scroll the mouse wheel to zoom while making an annotation.
