### ISSUE TITLE
tiff image open with nothing

### ISSUE THREAD

**Issue by mmlyj** [computationalpathologygroup/ASAP#150]
I downloads the windows binary  program,and use it to open a tiff image,the software work with no exception,but it shows nothing in pathology view. 
![image](https://user-images.githubusercontent.com/11947306/57424306-d26c4200-7249-11e9-9326-63f1039c0e24.png)

Actually ,I could open the tiff image with the ploting program in  accessory of windows 
![image](https://user-images.githubusercontent.com/11947306/57424339-e6b03f00-7249-11e9-865f-071bbfb93d12.png)

I git clone the source code and compile it on windows,and debug it. i found it exit when it calls  TIFFIsTiled in line 52 of  TIFFImage.cpp file.  i found if i comment that block , this function :MultiResolutionImage* TIFFImageFactory::readImage(const std::string& fileName)   return img normally,but it still shows nothing in pathology view. I am stuck in this problem, i am expected for  some advice

**Comment by APMraven** [comment]
I am having the same issue, please advise.

**Comment by GeertLitjens** [comment]
We only supported tiled, multi-resolution TIFF, so no single resolution TIFF files, quite sure that this is the case
