### ISSUE TITLE
Crash when opening new slide from slide /w altered labels

### ISSUE THREAD

**Issue by leandervaneekelen** [computationalpathologygroup/ASAP#151]
Minor bug.

**Issue**: when the currently open slide has unsaved new label data (i.e. a new PointSet, a new Group), opening a new slide will give the pop-up menu "The annotations have been modified. Do you want to save your changes?" Pressing 'cancel' (with the intention to abort the loading of the new slide) then triggers a crash of ASAP.

**Comment by GeertLitjens** [comment]
Should be fixed in the new version
