### ISSUE TITLE
python API

### ISSUE THREAD

**Issue by memphizz** [computationalpathologygroup/ASAP#154]
Is there a way to export annotated ROIs as numpy arrays? I have a few hundred images and 1000+ ROIs

**Comment by GeertLitjens** [comment]
You can get the pixel bounding box from the annotations and use getUCharPatch on the image to get the corresponding part of the image as a Numpy array (see here for an example: https://academic.oup.com/gigascience/article/7/6/giy065/5026175 how to handle annotations in Python)
