### ISSUE TITLE
Documentation for multiresolutionimageinterface to convert regular image to MR image.

### ISSUE THREAD

**Issue by darrenxuan** [computationalpathologygroup/ASAP#159]
I'm trying to convert a regular png/jpg image to multiresolutionimage that could be load by ASAP using python. I was trying to find document for multiresolutionimageinterface to see if there is such functions avaliable. 

I understand this is not a issue, but I could not find anywhere for help. Thank you for your understanding.

**Comment by GeertLitjens** [comment]
Hi, you could use some of the example code in this open-access paper, I think that should put you on the right track: https://academic.oup.com/gigascience/article/7/6/giy065/5026175
