### ISSUE TITLE
multiresolutionimageinterface mrxs read bug with python>=3.6.3

### ISSUE THREAD

**Issue by aswolinskiy** [computationalpathologygroup/ASAP#161]
multiresolutionimageinterface of asap 1.9.0 produces artefacts when reading mrxs images with python >=3.6.3
![example](https://user-images.githubusercontent.com/52372837/65597045-858acd00-df98-11e9-9bbc-956fad428815.jpg)

**Comment by martvanrijthoven** [comment]
I thinks this is a bug in pixman 0.38 which is shipped by anaconda and homebrew.

See:
https://github.com/openslide/openslide/issues/278

For me downgrading to pixman 0.36.0 fixed this issue (conda install pixman=0.36.0)

Extra note:
It seems that converting mrxs files to tif reduces the problem but actually it does not solve the problem.

**Comment by GeertLitjens** [comment]
Yes, it is a bug in libpixman
