### ISSUE TITLE
Unable to build the code in VS2017 and Windows 10

### ISSUE THREAD

**Issue by islam123786** [computationalpathologygroup/ASAP#163]
Hi,

I am quite new to CMake and i am not understanding how to build the code.
I would like to build the code for learning how the images are being read and rendered in qt.

Please point me to step by step document to build this code.

**Comment by GeertLitjens** [comment]
Hi, you could have a look at the readme.md in the root folder and the appveyor.yml in the root and Dockerfile in the buildtools folder. Other than that, I recommend following the tutorials and examples in the official CMake documentation
