### ISSUE TITLE
basicfilters_export.h: No such file

### ISSUE THREAD

**Issue by makatx** [computationalpathologygroup/ASAP#164]
Hi,
I'm trying to open the project in Qt in order to study the code and try to make some customization however so far I've had quite a bit to do in order to have it build successfully and now I'm stuck at the below error while building:
/asap-newproject/asap_qt/imgproc/basicfilters/FilterBase.h:4: error: basicfilters_export.h: No such file or directory
 #include "basicfilters_export.h"
                                 ^
I searched and could not find such a file myself in the project folders.
Thanks.

**Comment by GeertLitjens** [comment]
You need to run CMake to generate these files
