### ISSUE TITLE
how to use conda or pip install ASAP1.9 on windows?

### ISSUE THREAD

**Issue by VicJasonn** [computationalpathologygroup/ASAP#166]

**Comment by VicJasonn** [comment]
how can I use conda or pip to download ASAP directly from github? 
I wish to install it in my tensorflow environment and impot it in jupyter notebook.
Can anyone provide a solution? I will be grateful for it.

**Comment by GeertLitjens** [comment]
Hi, currently we do not build pip or conda packages as this is relatively complicated due to all the dependencies. When we have more time we will look into the new manylinux docker for building pip packages, but for the near future we will not support this
