### ISSUE TITLE
  Could NOT find OPENSLIDE (missing: OPENSLIDE_INCLUDE_DIR)

### ISSUE THREAD

**Issue by CapitalZe** [computationalpathologygroup/ASAP#169]
System:

Ubuntu 16.04 running via VMware on Macbook Pro.
Using VENV and Python3.

I had a similar problem with some other dependencies which have since been resolved, in this issue [#168](https://github.com/computationalpathologygroup/ASAP/issues/168).
There the problem was dependency versions.

In this case I think it is more of an OpenSlide issue, but am not certain.

When I try to compile ASAP this is the error thrown out:
`(MIDI) XXX@ubuntu:~/ASAP-1.9$ sudo cmake .
`

```
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OPENSLIDE (missing: OPENSLIDE_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmakemodules/FindOPENSLIDE.cmake:14 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:68 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/XXX/ASAP-1.9/CMakeFiles/CMakeOutput.log".
See also "/home/XXX/ASAP-1.9/CMakeFiles/CMakeError.log".
```

I've carefully gone over OpenSlide installation multiple times, ensuring to download and install OpenSlide, the dependencies and then the Python API. Regardless of execution I can not resolve the missing error.

I don't think it is a path argument issue, more so something to do with how OpenSlide is configured and it's directory hierarchy, but I cannot quite put my finger on it.

Has anyone else faced this or have some pointers?

**Comment by CapitalZe** [comment]
Additional note: if I run python from my venv, regardless of directory, and `import openslide` there are no errors.

**Comment by GeertLitjens** [comment]
You need to specify the directory where cmake can find openslide.h. See the readme for more generic instructions on how to use CMake to build ASAP

**Comment by GeertLitjens** [comment]
BTW, the instructions in .appveyor.yml and the Dockerfile in the buildtools folder might also help you
