### ISSUE TITLE
ASAP: command not found

### ISSUE THREAD

**Issue by wskmontaque** [computationalpathologygroup/ASAP#172]
Hi,
I've installed the Ubuntu 18.04 DEB version on my system. I've gone to the /opt/ASAP/bin/ and tried unsuccessfully to run ASAP.
see below:
(avl) dmontaque@HP1:~$ cd /opt
(avl) dmontaque@HP1:/opt$ cd ASAP
(avl) dmontaque@HP1:/opt/ASAP$ cd bin
(avl) dmontaque@HP1:/opt/ASAP/bin$ ASAP
ASAP: command not found
(avl) dmontaque@HP1:/opt/ASAP/bin$ 

Can you please confirm what the installation process should be? I have downloaded ASAP 1.9 DEB for 18.04 and it does not seem to work.
Thanks

**Comment by GeertLitjens** [comment]
Hi,

You need to type ./ASAP instead of ASAP

Kind regards,

Geert
