### ISSUE TITLE
Build error OpenJPEG

### ISSUE THREAD

**Issue by jcg9129** [computationalpathologygroup/ASAP#173]
I'm getting this error when try to build the library:

"
CMake Error at CMakeLists.txt:44 (find_package):
  By not providing "FindOpenJPEG.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenJPEG",
  but CMake did not find one.

  Could not find a package configuration file provided by "OpenJPEG" with any
  of the following names:

    OpenJPEGConfig.cmake
    openjpeg-config.cmake

  Add the installation prefix of "OpenJPEG" to CMAKE_PREFIX_PATH or set
  "OpenJPEG_DIR" to a directory containing one of the above files.  If
  "OpenJPEG" provides a separate development package or SDK, be sure it has
  been installed.
"

How can I fix this?

**Comment by GeertLitjens** [comment]
Hi, when you build OpenJPEG from source (or install it under Linux with something like apt), it will also install the .cmake files you mention. You have to specify OpenJPEG_DIR such that it points to the folder containing this file.
