### ISSUE TITLE
import multiresolutionimageinterface ERROR

### ISSUE THREAD

**Issue by githhhhh** [computationalpathologygroup/ASAP#174]
**When I try to import multiresolutionimageinterface, error occurs, PLEASE HELP**.

OS: Windows 10.0 (2004) 
developing platform: miniconda 3, python 3.7.7

I followed the **instruction**: **"add ASAP/bin to PYTHONPATH"**, and also tried **sys.path.append**.
**I tried ASAP==1.8 and ASAP==1.9, and tried another computer with the same environment**.
The same error occurs every time, here is the traceback below.

ImportError                               Traceback (most recent call last)
C:\Program Files\ASAP 1.8\bin\multiresolutionimageinterface.py in swig_import_helper()
     17         try:
---> 18             return importlib.import_module(mname)
     19         except ImportError:

~\miniconda3\lib\importlib\__init__.py in import_module(name, package)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 

~\miniconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\miniconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\miniconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\miniconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\miniconda3\lib\importlib\_bootstrap.py in module_from_spec(spec)

~\miniconda3\lib\importlib\_bootstrap_external.py in create_module(self, spec)

~\miniconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-88020922d507> in <module>
----> 1 import multiresolutionimageinterface as mir

C:\Program Files\ASAP 1.8\bin\multiresolutionimageinterface.py in <module>
     19         except ImportError:
     20             return importlib.import_module('_multiresolutionimageinterface')
---> 21     _multiresolutionimageinterface = swig_import_helper()
     22     del swig_import_helper
     23 elif _swig_python_version_info >= (2, 6, 0):

C:\Program Files\ASAP 1.8\bin\multiresolutionimageinterface.py in swig_import_helper()
     18             return importlib.import_module(mname)
     19         except ImportError:
---> 20             return importlib.import_module('_multiresolutionimageinterface')
     21     _multiresolutionimageinterface = swig_import_helper()
     22     del swig_import_helper

~\miniconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

ImportError: DLL load failed: 找不到指定的模块。(Can't find the specified module.)

**Comment by GeertLitjens** [comment]
Hi, I'm guessing it cannot find the DLLs. You need to add the ASAP/bin folder to your system path, either PATH on Windows or LD_LIBRARY_PATH on Linux. You can do that in code before the import if you don't want that permanently

**Comment by linchundan88** [comment]
I got the same error, I have added the /bin folder to PATH on Windows. ASAP1.9, Python3.7, Windows64.

**Comment by 110dazhi** [comment]
> I got the same error, I have added the /bin folder to PATH on Windows. ASAP1.9, Python3.7, Windows64.

 It only works on python3.6.8. I think. I tried 3.6.8 ,and it worked

**Comment by githhhhh** [comment]
> Hi, I'm guessing it cannot find the DLLs. You need to add the ASAP/bin folder to your system path, either PATH on Windows or LD_LIBRARY_PATH on Linux. You can do that in code before the import if you don't want that permanently

Thx! Never expected to receive a reply! I seldom read the messages on GitHub, maybe I need to do it more often now. For those who met the same error, first,  check the given advice above, if not work, then try to create a virtual environment with python version<3.7.

**Comment by Dhairya1510** [comment]
Still not working for me. I used python 3.6.8 and added the bin folder to PATH and PYTHONPATH. Also, I am using windows 11.
