### ISSUE TITLE
ASAP on Google Colab

### ISSUE THREAD

**Issue by jmayank23** [computationalpathologygroup/ASAP#182]
Is there a way to set this up on Google Colab Notebooks?

**Comment by vishnu-itachi** [comment]
Yes, there is.
First, check the ubuntu version instance u got in colab by typing
```bash 
!lsb_release -a
```
You will get something like this.
``` bash
No LSB modules are available.   
Distributor ID:	Ubuntu 
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

```
Then download the suitable deb package from [ASAP Releases](https://github.com/computationalpathologygroup/ASAP/releases)
In the above case, we need to download that 18.04 version
```bash
!wget https://github.com/computationalpathologygroup/ASAP/releases/download/1.9/ASAP-1.9-Linux-Ubuntu1804.deb
```
Then install the downloaded package 
```bash
!apt-get install "./ASAP-1.9-Linux-Ubuntu1804.deb"
```
Then you need to link the bin folder to the system path. You can find the path by using
```bash
!dpkg -L asap
```
Add the bin path
```bash
import sys
sys.path.insert(0,"/opt/ASAP/bin")
```
And that's. Now you should be able to use the python package.

**Comment by jmayank23** [comment]
Thank you so much @vishnu-itachi , I was able to install it and it's working fine

**Comment by vishnu-itachi** [comment]
> Thank you so much @vishnu-itachi , I was able to install it and it's working fine

Glad to help you!

**Comment by bnapora** [comment]
Thanks @vishnu-itachi  for the tip
