### ISSUE TITLE
How to install multiresolutionimageinterface on linux

### ISSUE THREAD

**Issue by MohammedHAlali** [computationalpathologygroup/ASAP#187]
Hello,
I'm trying to use multiresolutionimageinterface in Python on a linux machine.
I was able to run: 
`import multiresolutionimageinterface as mri`
But couldn't use any function inside mri.
For example, The following line doesn't work:
`image_reader = mri.MultiResolutionImageReader()`

I'm using Python 3.8 and I've cloned ASAP using git.
Here's a screenshot.
![mri](https://user-images.githubusercontent.com/33809125/93387065-3f282100-f82e-11ea-9311-6c07b1afcc52.PNG)

**Comment by christianabbet** [comment]
Hi,

I had the same issue. I ended up following the document [giy065](https://www.google.com/search?channel=fs&client=ubuntu&q=giy065.pdf) and it worked for me. I hope it will help.

**Comment by albayenes** [comment]
> Hello,
> I'm trying to use multiresolutionimageinterface in Python on a linux machine.
> I was able to run:
> `import multiresolutionimageinterface as mri`
> But couldn't use any function inside mri.
> For example, The following line doesn't work:
> `image_reader = mri.MultiResolutionImageReader()`
> 
> I'm using Python 3.8 and I've cloned ASAP using git.
> Here's a screenshot.
> ![mri](https://user-images.githubusercontent.com/33809125/93387065-3f282100-f82e-11ea-9311-6c07b1afcc52.PNG)

Which version do you use? I compiled on Ubuntu 20.04. As far as I know, you have to compile all of the ASAP.

**Comment by MohammedHAlali** [comment]
> 
> 
> > Hello,
> > I'm trying to use multiresolutionimageinterface in Python on a linux machine.
> > I was able to run:
> > `import multiresolutionimageinterface as mri`
> > But couldn't use any function inside mri.
> > For example, The following line doesn't work:
> > `image_reader = mri.MultiResolutionImageReader()`
> 
> Which versions of Linux and ASAP do you use? I compiled ASAP 1.9 on Ubuntu 20.04. As far as I know, you have to compile all of the ASAP.

Thanks for replying.
I'm using Red Hat 4.4 and I can only use the terminal.

How did you compile ASAP?

**Comment by albayenes** [comment]
> 
> Thanks for replying.
> I'm using Red Hat 4.4 and I can only use the terminal.
> I cloned this ASAP project and then tried to use it.
> 
> How did you compile ASAP? and How did you use it?

You should download source code of latest version. 

https://github.com/computationalpathologygroup/ASAP/archive/1.9.zip

Then you should install dependencies:

Boost (http://www.boost.org/)
OpenCV (http://www.opencv.org/)
Qt (http://www.qt.io/)
libtiff (http://www.libtiff.org/)
libjpeg (http://libjpeg.sourceforge.net/)
JasPer (http://www.ece.uvic.ca/~frodo/jasper/)
DCMTK (http://dicom.offis.de/dcmtk.php.en)
SWIG (http://www.swig.org/) (only for Python wrapping of the IO library)
OpenSlide (http://openslide.org/)
PugiXML (http://pugixml.org/)
zlib (http://www.zlib.net/)
unittest++ (https://github.com/unittest-cpp/unittest-cpp)

Then you can compile the source code using ccmake and make.

**Comment by HansPinckaers** [comment]
This issue can happen if you try to `import multiresolutionimageinterface` while being inside of the ASAP folder. Try adding `/opt/ASAP/bin` to your `PYTHONPATH` and try again.

**Comment by HansPinckaers** [comment]
Did you succeed in compiling ASAP from source? Maybe the dockerfile and build_asap.sh script can help you: https://github.com/computationalpathologygroup/ASAP/tree/develop/buildtools

**Comment by MohammedHAlali** [comment]
No, I couldn't run it.
I just created a new issue: 
https://github.com/computationalpathologygroup/ASAP/issues/209
Please take a look

**Comment by HansPinckaers** [comment]
Ok! I’m closing this issue now. Let’s continue there.
