### ISSUE TITLE
Where is the python script of multiresolutionimageinterface？And How to use it？

### ISSUE THREAD

**Issue by super233** [computationalpathologygroup/ASAP#192]
I have search all place but not found the python script of multiresolutionimageinterface, so where is it? Have it been removed in the latest version?

**Comment by GzrDavidRicardo** [comment]
Have you solved this question? I have encountered the same problem.

**Comment by super233** [comment]
Sorry, I have not.

**Comment by GeertLitjens** [comment]
It is in the ASAP bin dir, like before?
