### ISSUE TITLE
ModuleNotFoundError: No module named '_multiresolutionimageinterface'

### ISSUE THREAD

**Issue by super233** [computationalpathologygroup/ASAP#193]
When I use `import ASAP.bin.multiresolutionimageinterface as mri`, I encountered this? What's wrong? @GeertLitjens 

![image](https://user-images.githubusercontent.com/35358984/97535060-0024e800-19f6-11eb-81ff-063ae0cf0e81.png)

**Comment by albayenes** [comment]
which version of Linux do you use? Have installed ASAP using source code or package?
