### ISSUE TITLE
How to delete an annotation?

### ISSUE THREAD

**Issue by weiaicunzai** [computationalpathologygroup/ASAP#194]
Thanks for the great work,  I was just wandering how to delete a annotated label, all I've found is a "Clear" button which erase all the labels. I didn't find where the user manual is, is there a user manual? If there is, where can I find it? Thanks.

**Comment by ntomita** [comment]
You can press Delete for Windows and fn+option+delete for Mac. I see no manual exists (yet).

**Comment by weiaicunzai** [comment]
> You can press Delete for Windows and fn+option+delete for Mac. I see no manual exists (yet).

Ok, thanks for your replay.
