### ISSUE TITLE
Release for Ubuntu 20.04

### ISSUE THREAD

**Issue by wdeback** [computationalpathologygroup/ASAP#196]
Hi! 

Currently, ASAP 1.9 is packaged for Ubuntu 16.04 and 18.04: https://github.com/computationalpathologygroup/ASAP/releases

Is there a plan or time line for an official release for Ubuntu 20.04?

Thanks in advance!

**Comment by HansPinckaers** [comment]
Hi! I think you should be able to make a 20.04 release using the Docker, make sure to set the UBUNTU_VERSION on 20.04.

https://github.com/computationalpathologygroup/ASAP/blob/develop/buildtools/Dockerfile

**Comment by GeertLitjens** [comment]
You can also get them from here: https://ci.appveyor.com/project/GeertLitjens/asap (just click the build and then artifacts). Note these are not official releases, but continuous builds, so they might be less stable. Nonetheless, I think they should be mostly useable. For the next release, I will include an official Ubuntu 20.04 version.
