### ISSUE TITLE
Failed to open TIFF file for writing

### ISSUE THREAD

**Issue by WxpHB** [computationalpathologygroup/ASAP#198]
![图片](https://user-images.githubusercontent.com/47773138/103049175-f1107f80-45cb-11eb-8080-6411e1fc61c0.png)
Thanks for your excellent work! 
I use the code provided by the organizer，but when debug to the last line，it's can't convert .xml to .tif. and the   prompt message is“Failed to open TIFF file for writing ”，could you give me some clue？

**Comment by Yulu-gan** [comment]
I'm troubled by the same problem, too.
Have u solved this question?
Thanks for your sharing!
