### ISSUE TITLE
How to add openslide to CMake?

### ISSUE THREAD

**Issue by zhufl0811** [computationalpathologygroup/ASAP#200]

**Comment by zhufl0811** [comment]
CMake Error at CMakeLists.txt:80 (find_package):
  By not providing "FindOPENSLIDE.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "OPENSLIDE", but CMake did not find one.

  Could not find a package configuration file provided by "OPENSLIDE" with
  any of the following names:

    OPENSLIDEConfig.cmake
    openslide-config.cmake

  Add the installation prefix of "OPENSLIDE" to CMAKE_PREFIX_PATH or set
  "OPENSLIDE_DIR" to a directory containing one of the above files.  If
  "OPENSLIDE" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by albayenes** [comment]
The following works for me. I hope it helps you.

cmake .. -DBOOST_ROOT=G:/build_boost/boost_1_72_0 ^
-DQt5_DIR="C:/Qt/5.14.2/msvc2017_64/lib/cmake/Qt5" ^
-DOpenCV_DIR="C:/opencv/build" ^
-DOpenJPEG_DIR=C:/openjpeg-v2.4.0-windows-x64/lib/openjpeg-2.4  -A x64 ^
-DTIFF_LIBRARY="C:/Users/albayenes/anaconda3/Library/lib/tiff.lib" ^
-DOPENSLIDE_LIBRARY=E:/projects/ASAP/3rd-party/openslide/lib/libopenslide.lib -DOPENSLIDE_INCLUDE_DIR=E:/projects/ASAP/3rd-party/openslide/include/openslide ^
-DPugiXML_INCLUDE_DIR="C:/Program Files (x86)/pugixml/include" ^
-DBUILD_IMAGEPROCESSING=ON -DBUILD_EXECUTABLES=ON -DBUILD_ASAP=ON -DBUILD_MULTIRESOLUTIONIMAGEINTERFACE_VSI_SUPPORT=OFF


But the following gives linker error:

cmake .. -DBOOST_ROOT=G:/build_boost/boost_1_72_0 ^
-DQt5_DIR="C:/Qt/5.14.2/msvc2017_64/lib/cmake/Qt5" ^
-DOpenCV_DIR="C:/opencv/build" ^
-DDCMTKJPEG_LIBRARY=E:/projects/ASAP/3rd-party/dcmtk/lib/ijg8.lib -DDCMTKJPEG_INCLUDE_DIR=E:/projects/ASAP/3rd-party/dcmtk/include ^
-DOpenJPEG_DIR=C:/openjpeg-v2.4.0-windows-x64/lib/openjpeg-2.4  -A x64 ^
-DTIFF_LIBRARY="C:/Users/albayenes/anaconda3/Library/lib/tiff.lib" ^
-DOPENSLIDE_LIBRARY=E:/projects/ASAP/3rd-party/openslide/lib/libopenslide.lib -DOPENSLIDE_INCLUDE_DIR=E:/projects/ASAP/3rd-party/openslide/include/openslide ^
-DPugiXML_INCLUDE_DIR="C:/Program Files (x86)/pugixml/include" ^
-DBUILD_IMAGEPROCESSING=ON -DBUILD_EXECUTABLES=ON -DBUILD_ASAP=ON -DBUILD_MULTIRESOLUTIONIMAGEINTERFACE_VSI_SUPPORT=ON

ijg8.lib(jerror.obj) : error LNK2019: unresolved external symbol __imp___iob_func referenced in function output_message [E:\projects\ASAP\ASAP-develop\build\multiresolutionimageinterface\multiresolutionimageinterface.vcxproj]
  ijg8.lib(jerror.obj) : error LNK2019: unresolved external symbol __imp_sprintf referenced in function format_message [E:\projects\ASAP\ASAP-develop\build\multiresolutionimageinterface\multiresolutionimageinterface.vcxproj]
  E:\projects\ASAP\ASAP-develop\build\multiresolutionimageinterface\Debug\multiresolutionimageinterface_d.dll : fatal error LNK1120: 2 unresolved externals [E:\projects\ASAP\ASAP-develop\build\multiresolutionimageinterface\multiresoluti
onimageinterface.vcxproj]


I am trying to solve the linker error.
