### ISSUE TITLE
Error with closing multiresolutionimageinterface image

### ISSUE THREAD

**Issue by jeroenvermazeren** [computationalpathologygroup/ASAP#203]
When trying to close an image an error occurs. According to the error it is not possible to close the image as there is no function close for this image. 

Below the code, for privacy reasons I changed the image path to "*.tif"

```python 
from multiresolutionimageinterface import MultiResolutionImageReader

if __name__ == '__main__':
    mir_reader = MultiResolutionImageReader()
    wsi_multi = mir_reader.open('*.tif')
    wsi_multi.close()

```

Error traceback 

```python
Traceback (most recent call last):
  File "/home/jeroen/Documents/scratch/mart_test/main.py", line 6, in <module>
    wsi_multi.close()
AttributeError: 'MultiResolutionImage' object has no attribute 'close'

```

The error occurs on Ubuntu 20.04 with ASAP taken from https://ci.appveyor.com/project/GeertLitjens/asap and python 3.6.

**Comment by tomi2077** [comment]
Hi, I am currently installing ASAP and I haven't had any luck. I am using mac and downloaded the ASAP-1.9-Linux-Ubuntu1604.deb. I created a virtual environment and used pip install asap. 
I used sys.append('path of asap') to append the asap path nut I am unable to successfully import multiresolutionimageinterface.

**Comment by HansPinckaers** [comment]
Closing an image is not needed anymore. It’s done on garbage collection. If you want to force it you could `del` the variable.
