### ISSUE TITLE
Cannot attain mask from annotation using mir

### ISSUE THREAD

**Issue by CharlesSS07** [computationalpathologygroup/ASAP#205]
I have installed ASAP using the released deb 1.9 file on an ubuntu docker.
I have appended "/opt/ASAP/bin/" to my PYTHON_PATH, and can import multiresolutionimageinterface as mir and do inspection on it.

I have downloaded CAMELYON16 dataset from [here](https://drive.google.com/drive/folders/0BzsdkU4jWx9Bb19WNndQTlUwb2M?usp=sharing). This comes with annotations for the test data, which I am under the impression are legit.

I tried to follow code from the Camelyon16/17 paper [here](https://watermark.silverchair.com/giy065.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAArIwggKuBgkqhkiG9w0BBwagggKfMIICmwIBADCCApQGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkm-WxZ2A51qGfKAIAgEQgIICZZ-uS6HPBvceVzjY0esvtVmhLNEWjFuPZTpJ6l7WdRUlk2-pAGCO3Z9hyoMoDfOoCNuaFVJrN9cq2SJl7RhwDQXfGymqYDP92ee4g2Sy9BL5bCVFOi41HrJQxoBtXzK8WW1NXWN0MG4EAA0DdpX7O4PMDIX4n5mpfET0AAEfqpKjvl8Vv_aKEsqxIs7WBKlo11LLJMRh73IaONFOFMnjQDKPP_A_HhZvG5A8kyeNdnibCC_gl_ZiAAiWreGHmgpfhredr1proLCzebN2bafbMITXPdcuQgOhXMGkM_EqTnttMwiPXWY7D_qxiQs5j30PsF4KWIvUrPyYEA-LtwUzxWNtXEKCuGLZ1wn985uVtJREB1eaZV_lJkIp6_SLD9Gbn-qzgzCeHE7QMMOipj4jtoAkAadqZuaUCZGnaBya4NuDuhsUwd0TUMQ93YL7Ov2de_LMcpKvewgxG0S7EUSqEaGeS69w-nfHMnEJ1ZF-osEX5xS45sB9YQP8A0wKvLdPhzlsjx8kND3Q3qznqEeglfzFPe5Bbj88VpMxDc3MMg-Jnw8xGDXF9EIwStnGopQVcKoWY68hn6bMqnXsATIdDlMe50jYRN0hOZ7l3k5kDZ4loipbCr1ve5H6Fr7zZzOFEl0zADbF9-JEc3Iz6rKF0brjz6MZDPp-N5nbadd2xV9y1izfc1wzmhmbEWsmJgPXhz7OKocW-sDtIuGkzxfjeajG66NjyNyzfmYKOM0x12up_Y2jCeQE0WNJasquFQBpSN24SHHGIXE0bIQL8ZY3IcHXzLgaVJ8VWz9-0qL36Y4tjK8X_S8). However, this has resulted in getting masks which are completely 0, no matter what test XML file I use.

My code exactly:
```
make-mask.py:
#!/usr/bin/env python3

if __name__=='__main__':

    import argparse

    parser = argparse.ArgumentParser(description='Rasterize xml file for given slide in Camelyon dataset')
    parser.add_argument('tif_path', type=str)
    parser.add_argument('xml_path', type=str)
    parser.add_argument('out_path', type=str)

    args = parser.parse_args()

    import os

    print(f'Rasterizing {os.path.abspath(args.xml_path)} to {os.path.abspath(args.out_path)} with {os.path.abspath(args.tif_path)}')

    import sys

    sys.path.append('/opt/ASAP/bin/')

    import multiresolutionimageinterface as mir

    reader = mir.MultiResolutionImageReader()

    image = reader.open(os.path.abspath(args.tif_path))

    ann_list = mir.AnnotationList()

    xml_repo = mir.XmlRepository(ann_list)
    xml_repo.setSource(os.path.abspath(args.xml_path))
    xml_repo.load()

    annotation = ann_list.getAnnotation(0)
    print(annotation.getArea())
    print(annotation.getNumberOfPoints())
    print(annotation.getCoordinate(0).getX())

    ann_mask = mir.AnnotationToMask()

    label_map = {'metastases':1, 'normal':2}
    output_path = args.out_path
    ann_mask.convert(
            ann_list,
            output_path,
            image.getDimensions(),
            image.getSpacing(),
            label_map
    )
```

Run like so:
```
./make-mask.py ./CAMELYON16/testing/images/test_001.tif ./CAMELYON16/testing/lesion_annotations/test_001.xml ./wsi-masks/test_001.tif
```

Prints something like this:
```
Rasterizing /root/Downloads/lesion_annotations/test_001.xml to /root/wsi-masks/testing/test_001.tif with /root/Downloads/CAMELYON16/testing/images/test_001.tif
22879228.0 <--- area
1033 <--- number of coordinates
36904.30078125 <--- first x coordinate
Total time was 79820
Total reading time was 0
Total base writing time was 13544
Total pyramid downsampling time was 14
Total pyramid writing time was 66276
Total time determining min/max was 267
Traceback (most recent call last):
  File "./make-mask.py", line 43, in <module>
    ann_mask.convert(
  File "/opt/ASAP/bin/multiresolutionimageinterface.py", line 1949, in convert
    return _multiresolutionimageinterface.AnnotationToMask_convert(self, *args)
KeyboardInterrupt <--- I did not hit C^, so not me
Total time was 51869 <--- I'm guessing this is intentional and used as a callback? convert restarts here?
Total reading time was 0
Total base writing time was 3329
Total pyramid downsampling time was 0
Total pyramid writing time was 48540
Total time determining min/max was 307
```

Or (the output on another xml file--test_002.xml):
```
Rasterizing /root/Downloads/lesion_annotations/test_002.xml to /root/wsi-masks/testing/test_002.tif with /root/Downloads/CAMELYON16/testing/images/test_002.tif
18721860.0 <--- area
4745 <--- number of coordinates
34564.3984375 <--- first x coordinate
Total time was 138107
Total reading time was 0
Total base writing time was 1725
Total pyramid downsampling time was 14
Total pyramid writing time was 136382
Total time determining min/max was 18 <--- no keyboard interrupt this time?
```

And this produces a mask file, which has all the same levels and sizes as the input slide, but is "Grayscale", according to the `identify` command. The issue is that the mask should be an indexed version of the slide where 2 is normal, and 1 is metastasis. Right? The annotation object reports that the first lesion's area is much greater than 0. However, I get a slide that is fully 0, for any XML file.

I cannot find any documentation on the multiresolutionimageinterface. Please, any help is much appreciated.

Thank you for your time,
Charles.

**Comment by CharlesSS07** [comment]
Here is a solution that is clearly wrong, but got me what I wanted:
```
...
ann_mask.convert(
            ann_list,
            output_path,
            image.getDimensions(),
            image.getSpacing(),
            {} # <--- replace label_map with an empty dict
)
```
I apologize for the issue. Seems like I do not understand this parameter of `convert`. This resulted in a binary array, with 1 in the place of tumor, and 0 elsewhere.

**Comment by GeorgeBatch** [comment]
I had the same problem. It works to remove the label map. However, it also works to fix it:

`label_map = {'metastases':1, 'normal':2}` -> `label_map = {'Tumor':1, 'Normal':2}`

This helps because in `test_001.xml`, the group is called "Tumor" and not "metastasis":

```
<?xml version="1.0"?>
<ASAP_Annotations>
	<Annotations>
		<Annotation Name="Annotation 0" Type="Polygon" PartOfGroup="Tumor" Color="#F4FA58">
			<Coordinates>
				<Coordinate Order="0" X="36904.3" Y="66020.5" />
				<Coordinate Order="1" X="36862.1" Y="66004.9" />
...
```

**Note:** There are no "Normal" or "normal" polygons selected in `test_001.xml` Actually, there are no groups other than "Tumor". So I the capitalization of "Normal" is just for consistency.
