### ISSUE TITLE
most recent build doesn't overlay heatmaps correctly

### ISSUE THREAD

**Issue by aswolinskiy** [computationalpathologygroup/ASAP#214]
Left: correct with old asap release, right: the newest version
![Screenshot from 2021-08-26 10-03-51](https://user-images.githubusercontent.com/52372837/130925315-74effebe-3935-4a77-bb09-05d2947763b6.png)
Also, when opening a mask or heatmap directly, the new version just shows black. Old asap shows a tissue mask in shades of greay (probably internally rescaling masks with vaues usually in the range [0,5] or so to [0,255]

**Comment by Yihang6688** [comment]
Do you know how to resole this problem??I have encountered the same questions as yours.

**Comment by aswolinskiy** [comment]
I use the old (stable release) for viewing tifs/heatmaps and the new develop version for creating them.
