### ISSUE TITLE
does not find exe in bin (ubuntu 18.04)

### ISSUE THREAD

**Issue by JunMa11** [computationalpathologygroup/ASAP#222]
Dear @HansPinckaers ,

Thanks for sharing this great tool.

I installed the ASAP-2.0-py38 deb on ubuntu 18.04, but I do not find the exe file to open it.

![1636775557(1)](https://user-images.githubusercontent.com/19947331/141604721-493cbe4d-0963-4657-910c-4db39030abcf.png)

Any suggestions will be highly appreciated.

Best regards,
Jun

**Comment by HansPinckaers** [comment]
ASAP is not in your $PATH. Try “./ASAP” or add /opt/ASAP/bin to your path 👍

btw, @GeertLitjens is the maintainer and developer of ASAP 😊
