### ISSUE TITLE
docker build fails Ubuntu 20.04

### ISSUE THREAD

**Issue by jessecanada** [computationalpathologygroup/ASAP#224]
Step 18/20 : COPY build_ASAP.sh /root/build/build_ASAP.sh
COPY failed: file not found in build context or excluded by .dockerignore: stat build_ASAP.sh: file does not exist

**Comment by GeertLitjens** [comment]
Not sure what is going wrong, it works on my machine and on the build system. You could check the .appveyor.yml in the root of the repository to see if you are doing anything different that might cause this.
