### ISSUE TITLE
How to open file after using MultiResImageConverter

### ISSUE THREAD

**Issue by jessecanada** [computationalpathologygroup/ASAP#225]
After converting an image using the MultiResImageConverter, how do I open the resulting .tif file?

**Comment by GeertLitjens** [comment]
In Python you can do (make sure the ASAP bin folder is in your Pythonpath and that your system path contains the path to the shared libraries (e.g. LD_LIBRARY_PATH on Linux). Then you can do:

import multiresolutionimageinterface as mir
r = mir.MultiResolutionImageReader()
im = r.open(<path_to_slide>)
tile = im.getUCharPatch(0, 0, 512, 512, 6)

This will get you a tile from the image with the top-left at location 0,0, 512x512 pixels from level 6.

If you want to open it in the viewer, simply start the viewer (ASAP) and open the slide
