### ISSUE TITLE
"Invalid file type" when trying to open .tif from Camelyon16 challenge

### ISSUE THREAD

**Issue by alexkrz** [computationalpathologygroup/ASAP#226]
I have installed the ASAP-2.0-py38-Ubuntu2004.deb package on Ubuntu 20.04. When I try to open the .tif WSI from the Camelyon16 challenge I get the message "Invalid file type". Same happens on MacOS after installing ASAP-2.0-py38-Darwin.dmg. On Windows everything works after running the installer ASAP-2.0-py38-win64.exe. Any hints for fixes on Ubuntu and MacOS?

**Comment by GeertLitjens** [comment]
Most common reason is that you do not have the openslide package installed,
on Ubuntu you can do that with a simple apt-get, on MacOS I'm not sure, but
probably via homebrew or similar.

**Comment by alexkrz** [comment]
Unfortunately running 'apt-get install openslide-tools' could not fix the issue for me

**Comment by GeertLitjens** [comment]
There was a bug in the filename parsing code for Linux, it probably will work now

**Comment by alexkrz** [comment]
Confirmed, it's working now for me on Ubuntu20.04. Thank you!
