### ISSUE TITLE
MultiResolutionImageReader().open() problem

### ISSUE THREAD

**Issue by GzrDavidRicardo** [computationalpathologygroup/ASAP#228]
I use the multiresoluationimageinterface.MultiResolutionImageReader() block:

> self.image_path = '/home/gzr/code/NIC/data/CAMELYON16/one_tif'
> image_reader = mri.MultiResolutionImageReader()
> self.image = image_reader.open(self.image_path)
> self.image_shape = self.image.getLevelDimensions(self.image_level)
> self.image_level_multiplier = self.image.getLevelDimensions(0)[0] // self.image.getLevelDimensions(1)[0]

And the following problem occurs on the line 'self.image_shape = self.image.getLevelDimensions(self.image_level)':

**_'NoneType' object has no attribute 'getLevelDimensions'_**

**Comment by DecemberDecc** [comment]
I have encountered the same problem as you. How did you solve it?
