### ISSUE TITLE
Is there any tutorial for using multiresolutionimageinterface in python?

### ISSUE THREAD

**Issue by GzrDavidRicardo** [computationalpathologygroup/ASAP#229]

**Comment by GeertLitjens** [comment]
You can find some examples here:
https://academic.oup.com/gigascience/article/7/6/giy065/5026175?login=true

**Comment by GzrDavidRicardo** [comment]
Thanks.

**Comment by prerakmody** [comment]
I've also added an example [here](https://gist.github.com/prerakmody/9237b618c804ca9b99c1fd21e30de496) for the CAMELYON16 dataset (for breast cancer)

Note: There are also instructions on how to download the (partial) dataset from AWS .

**Comment by GeertLitjens** [comment]
Supernice, thanks!

Op do 24 nov. 2022 om 14:09 schreef pmod ***@***.***>:
