### ISSUE TITLE
Convert .jpg to .svs or .tif

### ISSUE THREAD

**Issue by XinyeDu77** [computationalpathologygroup/ASAP#243]
I want to use ASAP to annotation pathological image. But the format of my images are jpg, do some people know how to convert .jpg to .svs or .tif?
Thank you very much!!!

**Comment by GeertLitjens** [comment]
There are some instructions that you can take from this paper,: https://academic.oup.com/gigascience/article/7/6/giy065/5026175 just read in your .jpg with PIL and convert it to a numpy array.
