### ISSUE TITLE
Confusion about building projects

### ISSUE THREAD

**Issue by while-lin** [computationalpathologygroup/ASAP#245]
I built the ASAP 2.0 according to the steps, and used the library provided in the project. After building, an EXE file can be generated, but most of the buttons and picture viewing boxes are missing
![pic](https://user-images.githubusercontent.com/52849152/189274371-45b6e072-0b63-445d-82dd-dd19e90da6d7.png)
I used visual studio2019, Cmake 3.24.0 to build this project.
Could you please send me an project that has been built (asa[ 2.0)? I want to make a comparison to see what mistakes I made in building the project, just for study. I am a student who has recently started learning cmake,Thanks!

**Comment by GeertLitjens** [comment]
You need to build the INSTALL target, which copies all the relevant DLLs and plugins to the right location. From there you can start the program through the .exe

**Comment by WxpHB** [comment]
@while-lin  do you solve the problem? I have the same problem,could you help me out?
