### ISSUE TITLE
Unable to open ndpi file

### ISSUE THREAD

**Issue by Dr-Yi-Li** [computationalpathologygroup/ASAP#247]
ASAP 2.1
Python 3.9
Windows 11

import multiresolutionimageinterface as mir
reader = mir.MultiResolutionImageReader()
mr_image = reader.open('C:\\Users\\moorz\\PycharmProjects\\py39_tor112_cuda116\\1115788_2021-06-09 10.10.16.ndpi')

I cannot load my ndpi file based on the above code with absolute or relative paths.
The mr_image shows mr_image = {NoneType} None
Could you please help me solve the problem?

![image](https://user-images.githubusercontent.com/35036213/194717103-5fdeaa9a-00fa-479e-b0a4-fbab45a933a0.png)
![image](https://user-images.githubusercontent.com/35036213/194717109-3c126d86-d739-4258-a365-9fb8fe7e58d1.png)

**Comment by GeertLitjens** [comment]
We use OpenSlide as the backend for NDPI files, and it had some known
issues with certain gives, see for example
https://github.com/openslide/openslide/issues/272. Please check if you can
open the file with openslide-python, if that doesn't work you will need to
file a bug report with openslide

**Comment by Dr-Yi-Li** [comment]
Thanks!

**Comment by Dr-Yi-Li** [comment]
Thanks! @GeertLitjens
