### ISSUE TITLE
import errror: libannotation.so

### ISSUE THREAD

**Issue by AmnaahmedGillaniQC** [computationalpathologygroup/ASAP#248]
I am trying to install ASAP from the compiled binary for python 3.8 as multiresolutionimageinterface is a dependency for pythostitcher (https://github.com/computationalpathologygroup/pythostitcher)

However, I am getting the following error when importing multiresolutionimageinterface.py:
```
  File "multiresolutionimageinterface.py", line 15, in <module>
    import _multiresolutionimageinterface
ImportError: libannotation.so: cannot open shared object file: No such file or directory
```
I am running this in a docker container with Ubuntu 20.04 and python 3.8.10

Any idea how to resolve this?

**Comment by GeertLitjens** [comment]
The ASAP library folder needs to be in your LD_LIBRARY_PATH, otherwise
python will not know where to find the libraries (/opt/ASAP).

Kind regards,

Geert

Op wo 9 nov. 2022 om 10:23 schreef AmnaahmedGillaniQC <
***@***.***>:
