### ISSUE TITLE
not compatible with openslide

### ISSUE THREAD

**Issue by 464hee** [computationalpathologygroup/ASAP#250]
Using the multi-level tif file generated by ASAP, there is an obvious error in the openslide reading. I want to know about ASAP is built on top of several well-developed open source packages like OpenSlide, Qt and OpenCV but also tries to extend them in several meaningful ways.
Why the generated tif file is not compatible with openslide

openslide-python==1.2.0
openslide==3.4.1
[data_and_code.zip](https://github.com/computationalpathologygroup/ASAP/files/10055087/data_and_code.zip)

asap=2.1
python=3.9

**Comment by 464hee** [comment]
@HansPinckaers @hmeine @wouterbulten @Karelger Look forward to your reply

**Comment by GeertLitjens** [comment]
You are writing a monochrome (i.e. single gray value) image, which openslide doesn't support
