### ISSUE TITLE
Default Cancer detection visualization Window / Level settings

### ISSUE THREAD

**Issue by peterbandi** [computationalpathologygroup/ASAP#6]
Setting the right Window and Level values for visualizing heat maps is not straightforward. It would be nice to have some kind of default settings for ranges: [0, 255] uint8 and [0.0, 1.0] float32. A more clear setting method or at least a formula description in a tool tip for any arbitrary interval would be also very useful.

**Comment by peterbandi** [comment]
Furthermore a displayed palette would be really useful. And a more intuitive Min/Max setting instead of the Window/Level.

**Comment by GeertLitjens** [comment]
Fixed in the new version
