### ISSUE TITLE
Update installation guide

### ISSUE THREAD

**Issue by Vozf** [computationalpathologygroup/ASAP#72]
Please update installation guide with a guide to launching(at least viewer). From the current guide it is completely unclear what to do after installing deb package. Nothing can be found on the internet. So you basically have to guess how to launch viewer as no command 'asap' appears on the terminal. Spend ~ 2 hours figuring out how to open viewer trying to install different .deb files hoping for some terminal command to appear before locating installation folder.
Completely unclear instructions

**Comment by GeertLitjens** [comment]
We know documentation is currently lacking, we are working on it

**Comment by Vozf** [comment]
launch /opt/ASAP/bin/ASAP

**Comment by vladvroust** [comment]
Thx @Vozf ! I've been installing several .deb, how was getting discouraged

**Comment by sbelharbi** [comment]
> launch /opt/ASAP/bin/ASAP

I think this needs to be added somewhere in the documentation if it is not already there (at least in the github page). I didn't know that it was installed in /opt. My mistake ($ locate ASAP).

**Comment by Vozf** [comment]
Why is this getting closed when nothing was done?

**Comment by GeertLitjens** [comment]
The readme.md was updated to reflect the location of the executable
