### ISSUE TITLE
.svs files

### ISSUE THREAD

**Issue by maor121** [computationalpathologygroup/ASAP#84]
Just installed the .deb package on Ubuntu and launched the GUI with /opt/ASAP/bin/ASAP from the terminal. However supported files (when trying to open something), do not include .svs files.

I saw code examples (python wrapper) on github that read .svs files, does the UI version not support reading them?

**Comment by GeertLitjens** [comment]
Hi, please make sure you have libopenslide installed, otherwise formats like SVS do not work

**Comment by maor121** [comment]
Thank you! It works :)
