### ISSUE TITLE
How to use MultiResolutionImageWriter ?

### ISSUE THREAD

**Issue by FarhadGZ** [computationalpathologygroup/ASAP#85]
I can read image tiles from a multiresolution WSI by using "MultiResolutionImageReader" and "getUCharPatch" commands.

How can I write the modified image tiles into a new WSI by using MultiResolutionImageWriter command?
Providing a python example is very helpful.

**Comment by GeertLitjens** [comment]
Hi,

We now have some example in our recently published article on the CAMELYON dataset: https://academic.oup.com/gigascience/advance-article/doi/10.1093/gigascience/giy065/5026175?searchresult=1 

We will soon at more to the website
