### ISSUE TITLE
ASAP not recognising tif files, throws error message "invalid file type"

### ISSUE THREAD

**Issue by omayrakhtar** [computationalpathologygroup/ASAP#87]
I am trying to annotate some converted tif files using ASAP. These tif files are originally converted from Carl Zeiss czi format. Unfortunately, for some reason  ASAP doesn't recognise the format and throws 'invalid file type' error. I am suspecting that there are some mandatory file headers that it looks for which are not there in the tif (converted from czi) files, if so, please mention those headers in the documentation.

**Comment by GeertLitjens** [comment]
Hi, which software did you use to convert them?

**Comment by omayrakhtar** [comment]
Zen Lite from Carl Zeiss and ImageJ by Fiji. And I tried different options like lossy, lossless, 8-bit/16-bit and also variants of tif like bigtif, ome-tif and etc.

**Comment by omayrakhtar** [comment]
Thank you. I'll try generic-tiff and share the results here.

**Comment by omayrakhtar** [comment]
Converting czi to generic-tiff solved the problem. Thank you for the suggestion.

**Comment by lei1993** [comment]
@omayrakhtar What's the converter?

**Comment by omayrakhtar** [comment]
@lei1993 I used [Zen Lite](https://www.zeiss.com/microscopy/int/products/microscope-software/zen-lite.html).

**Comment by laurapurcaro-bit** [comment]
Hello, I am trying to open a segmented .tif asap file with python but is not working. Do you have any suggestion how I could open the file? Thank you

**Comment by hanwang365** [comment]
@omayrakhtar  Hi. I ran into a similar problem. I want to convert some jp2 images to TIFF images which could be recognized by ASAP, and I use many methods, such as MATLAB, openjpeg. However, the generated TIFF images were 'invalid file type' by ASAP. So, I want to consult that how to generate generic-tiff? Is there any optional functions in the software that you used?

**Comment by omayrkhan** [comment]
@hanwang365 I converted Ziess proprietary format to generic-tiff using their own scanning software. One thing I remember is that ASAP accepts tiffs with a pyramid-like structure. Make sure you're taking that into consideration.
