### ISSUE TITLE
Unable to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by stefanknegt** [computationalpathologygroup/ASAP#92]
I get the following error when installing using: 'sudo dpkg -i ASAP-1.8-python36-Linux.deb'

(Reading database ... 213998 files and directories currently installed.)
Preparing to unpack ASAP-1.8-python36-Linux.deb ...
Unpacking asap (1.8) over (1.8) ...
dpkg: dependency problems prevent configuration of asap:
 asap depends on libboost-filesystem1.58.0; however:
  Package libboost-filesystem1.58.0 is not installed.
 asap depends on libboost-program-options1.58.0; however:
  Package libboost-program-options1.58.0 is not installed.
 asap depends on libboost-regex1.58.0; however:
  Package libboost-regex1.58.0 is not installed.
 asap depends on libboost-system1.58.0; however:
  Package libboost-system1.58.0 is not installed.
 asap depends on libboost-thread1.58.0; however:
  Package libboost-thread1.58.0 is not installed.
 asap depends on libdcmtk5; however:
  Package libdcmtk5 is not installed.
 asap depends on libjasper1; however:
  Package libjasper1 is not installed.

dpkg: error processing package asap (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 asap

Could you please fix this?

**Comment by 9xg** [comment]
I am facing the exact same issue!

**Comment by stefanknegt** [comment]
I went back to 16.04 and that 'of course' fixed the issue for now.

**Comment by GeertLitjens** [comment]
The current deb package was compile on 16.04. The libraries it depends on are not present in the 18.04 repositories. We are working on making a 18.04 version, but as libjasper is no longer part of the Ubuntu repos, we need to replace it and that is why it is taking more time. The other solution is to compile it yourself on Ubuntu 18.04 for now.
