### ISSUE TITLE
How long does it take a file to load, and how much memory

### ISSUE THREAD

**Issue by rawatenator** [computationalpathologygroup/ASAP#93]
I was trying to load a VSI image, it took over 10 minutes before crashing. Used approx 60GB of ram (I have 120GB on the machine). is this kind of time/memory usage standard?

**Comment by GeertLitjens** [comment]
Hi, VSI can currently not be opened in the viewer as we only have access to the highest resolution and not to the multi-resolution pyramid. You can convert it to TIFF and open it with the MultiResolutionImageConverter (in the ASAP install folder)
