### ISSUE TITLE
XML files not showing

### ISSUE THREAD

**Issue by aris-ang** [computationalpathologygroup/ASAP#97]
Hello,

I am trying to load an annotation xml file by pressing the load button. I choose the file to load but when i click open, no annotations are loaded. This is very peculiar since i had no trouble loading xml files when i ran ASAP on other computers, even when i tried loading the exact same xml files. The xml files were created on ASAP. Do you know what the problem might be? I run ASAP 1.8.1 on windows 10 64-bit. Any help would be greatly appreciated.

EDIT: while playing around with the GUI, i also found out that i can't save any new annotations, besides loading existing ones. An error window pops up, with the message "The annotations could not be saved".

**Comment by liyu10000** [comment]
Hi bro, I run into the same problem. Have you found a solution?

**Comment by aris-ang** [comment]
Turns out it was a windows issue. The user i was using didn't have proper authorisation to run the program after installing. I changed that from the executable's properties and everything ran smoothly. Since there was no real problem, i am closing this issue.

**Comment by Acmenwangtuo** [comment]
Hello，bro，Can you tell me how you solve the problem?
